// Generates lib/core/time/lume_zone_aliases.dart from the pinned `timezone`
// package: which identifiers in `latest_all` are IANA's canonical zones, and
// which are backward links, each with the canonical zone it names. Then
// lib/core/time/lume_country_zones.dart: each country's zones (CLDR's list,
// scripts/data/cldr_country_zones.json), and the zone of the countries whose
// list is exactly one canonical zone; and
// lib/core/time/lume_zone_labels_data.dart, each zone's CLDR location label
// in the app's languages.
//
//   node scripts/cldr_country_zones.mjs      (only when CLDR is updated)
//   dart run scripts/generate_zone_aliases.dart
//
// Run only as part of a deliberate tzdb update (WORLD_CLOCK_TIMEZONE.md,
// "Updating the database"), and review the diff it produces.
//
// A link in the compiled database is a copy of its target's rules, so the
// identifiers that share one set of rules are one zone and its links. The
// canonical member of each set is the one the package lists among its
// canonical locations (generated from IANA's own zone list); the rest are
// aliases of it. A set with no listed member keeps every member as canonical
// — no alias is invented.

// The package's canonical list is not exported; this script, not the app,
// reads it.
// ignore: implementation_imports
import 'package:timezone/src/common_locations.dart' as tz_common;
import 'package:timezone/data/latest_all.dart' as tz_data;
import 'package:timezone/timezone.dart' as tz;
import 'dart:convert';
import 'dart:io';

String _signature(tz.Location l) => <String>[
  l.transitionAt.join(','),
  l.transitionZone.join(','),
  for (final tz.TimeZone z in l.zones)
    '${z.offset.inSeconds}/${z.isDst}/${z.abbreviation}',
].join('|');

void main() {
  tz_data.initializeTimeZones();
  final Map<String, tz.Location> all = tz.timeZoneDatabase.locations;
  final Set<String> listed = tz_common.commonLocations.toSet();

  final Map<String, List<String>> bySignature = <String, List<String>>{};
  for (final tz.Location l in all.values) {
    (bySignature[_signature(l)] ??= <String>[]).add(l.name);
  }

  final Map<String, String> aliases = <String, String>{};
  final Set<String> canonical = <String>{};
  for (final List<String> names in bySignature.values) {
    final List<String> heads = names.where(listed.contains).toList();
    if (heads.length != 1) {
      canonical.addAll(names);
      continue;
    }
    canonical.add(heads.single);
    for (final String n in names) {
      if (n != heads.single) aliases[n] = heads.single;
    }
  }

  final List<String> a = aliases.keys.toList()..sort();
  final List<String> c = canonical.toList()..sort();
  final StringBuffer out = StringBuffer()
    ..writeln(
      '// GENERATED by scripts/generate_zone_aliases.dart — do not edit.',
    )
    ..writeln(
      '// Timezone package 0.11.1, tzdb 2025c, data variant latest_all.',
    )
    ..writeln('// ${c.length} canonical identifiers, ${a.length} aliases.')
    ..writeln()
    ..writeln('/// The tzdb release these tables were generated from.')
    ..writeln("const String kLumeTzdbVersion = '2025c';")
    ..writeln()
    ..writeln('/// Backward links, each to the canonical zone it names.')
    ..writeln('const Map<String, String> kLumeZoneAliases = <String, String>{');
  for (final String k in a) {
    out.writeln("  '$k': '${aliases[k]}',");
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln('/// The canonical identifiers — what a new selection stores.')
    ..writeln('const Set<String> kLumeCanonicalZones = <String>{');
  for (final String k in c) {
    out.writeln("  '$k',");
  }
  out.writeln('};');
  File(
    'lib/core/time/lume_zone_aliases.dart',
  ).writeAsStringSync(out.toString());
  stdout.writeln(
    'wrote ${c.length} canonical, ${a.length} aliases, '
    '${all.length} identifiers in the database',
  );
  _countries(aliases, canonical);
}

/// A country's region zone exists only when every zone CLDR lists for it is
/// one canonical identity — the identifier itself, or links to it. Two
/// canonical zones are never merged because their offsets agree today (or
/// over any window): Berlin and Büsingen, or Kazakhstan's zones, stay
/// distinct, and a reader there with no city chooses.
void _countries(Map<String, String> aliases, Set<String> canonical) {
  final Map<String, dynamic> cldr =
      jsonDecode(
            File('scripts/data/cldr_country_zones.json').readAsStringSync(),
          )
          as Map<String, dynamic>;
  String? canon(String id) => canonical.contains(id) ? id : aliases[id];

  final Map<String, List<String>> zones = <String, List<String>>{};
  final Map<String, List<String>> listedIds = <String, List<String>>{};
  final Map<String, String> single = <String, String>{};
  final Map<String, dynamic> listed = cldr['zones'] as Map<String, dynamic>;
  for (final String code in (listed.keys.toList()..sort())) {
    final List<String> raw = <String>[
      for (final dynamic id in listed[code] as List<dynamic>)
        if (canon(id as String) != null) id,
    ]..sort();
    final List<String> ids = <String>{
      for (final String id in raw) canon(id)!,
    }.toList()..sort();
    if (ids.isEmpty) continue;
    zones[code] = ids;
    listedIds[code] = raw;
    if (ids.length == 1) single[code] = ids.single;
  }

  final List<String> several = <String>[
    for (final String k in zones.keys)
      if (!single.containsKey(k)) k,
  ];
  String list(List<String> v) =>
      '<String>[${v.map((String z) => "'$z'").join(', ')}]';
  final StringBuffer out = StringBuffer()
    ..writeln(
      '// GENERATED by scripts/generate_zone_aliases.dart — do not edit.',
    )
    ..writeln(
      '// Zones per country: CLDR ${cldr['cldr']} (ICU ${cldr['icu']}), '
      'canonicalised against tzdb 2025c.',
    )
    ..writeln(
      '// A country has a zone of its own only when its list is one '
      'canonical zone.',
    )
    ..writeln(
      '// ${zones.length} countries; ${single.length} with one canonical '
      'zone; ${several.length} with more.',
    )
    ..writeln()
    ..writeln('/// The CLDR release the country lists come from.')
    ..writeln("const String kLumeCountryZonesCldr = '${cldr['cldr']}';")
    ..writeln()
    ..writeln('/// Every canonical zone CLDR lists for a country.')
    ..writeln(
      'const Map<String, List<String>> kLumeCountryZones = '
      '<String, List<String>>{',
    );
  for (final MapEntry<String, List<String>> e in zones.entries) {
    out.writeln("  '${e.key}': ${list(e.value)},");
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln(
      '/// The identifiers exactly as CLDR lists them for a country — links',
    )
    ..writeln(
      '/// included (`Asia/Kuwait`) — for its labels, never its identity.',
    )
    ..writeln(
      'const Map<String, List<String>> kLumeCountryZoneIds = '
      '<String, List<String>>{',
    );
  for (final MapEntry<String, List<String>> e in listedIds.entries) {
    out.writeln("  '${e.key}': ${list(e.value)},");
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln(
      '/// The zone of a country whose list is one canonical zone — absent',
    )
    ..writeln('/// for a country with several (${several.join(', ')}).')
    ..writeln('const Map<String, String> kLumeCountryZone = <String, String>{');
  for (final MapEntry<String, String> e in single.entries) {
    out.writeln("  '${e.key}': '${e.value}',");
  }
  out.writeln('};');
  File(
    'lib/core/time/lume_country_zones.dart',
  ).writeAsStringSync(out.toString());
  stdout.writeln(
    'wrote ${zones.length} countries, ${single.length} with one canonical '
    'zone: several in ${several.join(',')}',
  );
  _labels(cldr);
}

void _labels(Map<String, dynamic> cldr) {
  final Map<String, dynamic> labels = cldr['labels'] as Map<String, dynamic>;
  String quote(String s) =>
      "'${s.replaceAll(r'\', r'\').replaceAll("'", r"\'")}'";
  final StringBuffer out = StringBuffer()
    ..writeln(
      '// GENERATED by scripts/generate_zone_aliases.dart — do not edit.',
    )
    ..writeln(
      '// CLDR ${cldr['cldr']} (ICU ${cldr['icu']}) generic location labels: '
      'the country, or the',
    )
    ..writeln(
      "// zone's exemplar city. A zone absent here has no label; the "
      'identifier shows.',
    )
    ..writeln()
    ..writeln("/// CLDR's generic location pattern per language: '{0} Time'.")
    ..writeln(
      'const Map<String, String> kLumeZoneLabelFormat = <String, String>{',
    );
  final Map<String, dynamic> formats = cldr['formats'] as Map<String, dynamic>;
  for (final String lang in (formats.keys.toList()..sort())) {
    out.writeln("  '$lang': ${quote(formats[lang] as String)},");
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln('/// Location labels by language, then by IANA identifier.')
    ..writeln(
      'const Map<String, Map<String, String>> kLumeZoneLabelText = '
      '<String, Map<String, String>>{',
    );
  int count = 0;
  for (final String lang in (labels.keys.toList()..sort())) {
    final Map<String, dynamic> m = labels[lang] as Map<String, dynamic>;
    out.writeln("  '$lang': <String, String>{");
    for (final String id in (m.keys.toList()..sort())) {
      out.writeln('    ${quote(id)}: ${quote(m[id] as String)},');
      count++;
    }
    out.writeln('  },');
  }
  out.writeln('};');
  File(
    'lib/core/time/lume_zone_labels_data.dart',
  ).writeAsStringSync(out.toString());
  stdout.writeln('wrote $count labels in ${labels.length} languages');
}
