// Generates lib/core/time/lume_zone_aliases.dart from the pinned `timezone`
// package: which identifiers in `latest_all` are IANA's canonical zones, and
// which are backward links, each with the canonical zone it names. Then
// lib/core/time/lume_country_zones.dart: each country's zones (CLDR's list,
// scripts/data/cldr_country_zones.json), and the one civil time of the
// countries that have exactly one.
//
//   node scripts/cldr_country_zones.mjs      (only when CLDR is updated)
//   dart run scripts/generate_zone_aliases.dart
//
// Run only as part of a deliberate tzdb update (WORLD_CLOCK_TIMEZONE.md,
// "Updating the database"), and review the diff it produces.
//
// A link in the compiled database is a copy of its target's rules, so the
// identifiers that share one set of rules are one zone and its links. The
// canonical member of each set is the one the package lists among its
// canonical locations (generated from IANA's own zone list); the rest are
// aliases of it. A set with no listed member keeps every member as canonical
// — no alias is invented.

// The package's canonical list is not exported; this script, not the app,
// reads it.
// ignore: implementation_imports
import 'package:timezone/src/common_locations.dart' as tz_common;
import 'package:timezone/data/latest_all.dart' as tz_data;
import 'package:timezone/timezone.dart' as tz;
import 'dart:convert';
import 'dart:io';

String _signature(tz.Location l) => <String>[
  l.transitionAt.join(','),
  l.transitionZone.join(','),
  for (final tz.TimeZone z in l.zones)
    '${z.offset.inSeconds}/${z.isDst}/${z.abbreviation}',
].join('|');

void main() {
  tz_data.initializeTimeZones();
  final Map<String, tz.Location> all = tz.timeZoneDatabase.locations;
  final Set<String> listed = tz_common.commonLocations.toSet();

  final Map<String, List<String>> bySignature = <String, List<String>>{};
  for (final tz.Location l in all.values) {
    (bySignature[_signature(l)] ??= <String>[]).add(l.name);
  }

  final Map<String, String> aliases = <String, String>{};
  final Set<String> canonical = <String>{};
  for (final List<String> names in bySignature.values) {
    final List<String> heads = names.where(listed.contains).toList();
    if (heads.length != 1) {
      canonical.addAll(names);
      continue;
    }
    canonical.add(heads.single);
    for (final String n in names) {
      if (n != heads.single) aliases[n] = heads.single;
    }
  }

  final List<String> a = aliases.keys.toList()..sort();
  final List<String> c = canonical.toList()..sort();
  final StringBuffer out = StringBuffer()
    ..writeln(
      '// GENERATED by scripts/generate_zone_aliases.dart — do not edit.',
    )
    ..writeln(
      '// Timezone package 0.11.1, tzdb 2025c, data variant latest_all.',
    )
    ..writeln('// ${c.length} canonical identifiers, ${a.length} aliases.')
    ..writeln()
    ..writeln('/// The tzdb release these tables were generated from.')
    ..writeln("const String kLumeTzdbVersion = '2025c';")
    ..writeln()
    ..writeln('/// Backward links, each to the canonical zone it names.')
    ..writeln('const Map<String, String> kLumeZoneAliases = <String, String>{');
  for (final String k in a) {
    out.writeln("  '$k': '${aliases[k]}',");
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln('/// The canonical identifiers — what a new selection stores.')
    ..writeln('const Set<String> kLumeCanonicalZones = <String>{');
  for (final String k in c) {
    out.writeln("  '$k',");
  }
  out.writeln('};');
  File(
    'lib/core/time/lume_zone_aliases.dart',
  ).writeAsStringSync(out.toString());
  stdout.writeln(
    'wrote ${c.length} canonical, ${a.length} aliases, '
    '${all.length} identifiers in the database',
  );
  _countries(aliases, canonical);
}

/// The window two zones must agree over, hour by hour, to be one civil time:
/// five years from the start of 2026. Zones that differed in the past and
/// agree now (Kazakhstan since 2024, Berlin and Büsingen) are one civil time;
/// zones a scheduled rule change will split are not.
final DateTime _from = DateTime.utc(2026);
final DateTime _to = DateTime.utc(2031);

bool _sameCivilTime(tz.Location a, tz.Location b) {
  for (
    DateTime t = _from;
    t.isBefore(_to);
    t = t.add(const Duration(hours: 1))
  ) {
    final int ms = t.millisecondsSinceEpoch;
    if (a.timeZone(ms).offset != b.timeZone(ms).offset) return false;
  }
  return true;
}

void _countries(Map<String, String> aliases, Set<String> canonical) {
  final Map<String, dynamic> cldr =
      jsonDecode(
            File('scripts/data/cldr_country_zones.json').readAsStringSync(),
          )
          as Map<String, dynamic>;
  final Map<String, dynamic> table =
      jsonDecode(File('assets/data/countries.json').readAsStringSync())
          as Map<String, dynamic>;
  final Map<String, String> tableZone = <String, String>{
    for (final dynamic c in table['countries'] as List<dynamic>)
      (c as Map<String, dynamic>)['code'] as String:
          (c['timezone'] as String?) ?? '',
  };
  String? canon(String id) => canonical.contains(id) ? id : aliases[id];

  final Map<String, List<String>> zones = <String, List<String>>{};
  final Map<String, String> civil = <String, String>{};
  final Map<String, int> civilCount = <String, int>{};
  final Map<String, dynamic> listed = cldr['zones'] as Map<String, dynamic>;
  for (final String code in (listed.keys.toList()..sort())) {
    final List<String> ids = <String>{
      for (final dynamic id in listed[code] as List<dynamic>)
        ?canon(id as String),
    }.toList()..sort();
    if (ids.isEmpty) continue;
    zones[code] = ids;
    // Group into civil times, each led by its first member.
    final List<List<String>> groups = <List<String>>[];
    for (final String id in ids) {
      final tz.Location l = tz.getLocation(id);
      final List<String>? home = groups
          .where((List<String> g) => _sameCivilTime(tz.getLocation(g.first), l))
          .firstOrNull;
      if (home == null) {
        groups.add(<String>[id]);
      } else {
        home.add(id);
      }
    }
    civilCount[code] = groups.length;
    if (groups.length != 1) continue;
    // The country table's own zone leads when it is one of them.
    final String? own = canon(tableZone[code] ?? '');
    civil[code] = own != null && groups.single.contains(own)
        ? own
        : groups.single.first;
  }

  final List<String> several = <String>[
    for (final String k in zones.keys)
      if (!civil.containsKey(k)) k,
  ];
  final StringBuffer out = StringBuffer()
    ..writeln(
      '// GENERATED by scripts/generate_zone_aliases.dart — do not edit.',
    )
    ..writeln(
      '// Zones per country: CLDR ${cldr['cldr']} (ICU ${cldr['icu']}), '
      'canonicalised against tzdb 2025c.',
    )
    ..writeln(
      '// One civil time: offsets equal hour by hour, 2026 to 2031 (UTC).',
    )
    ..writeln(
      '// ${zones.length} countries; ${civil.length} with one civil time; '
      '${several.length} with more.',
    )
    ..writeln()
    ..writeln('/// The CLDR release the country lists come from.')
    ..writeln("const String kLumeCountryZonesCldr = '${cldr['cldr']}';")
    ..writeln()
    ..writeln('/// Every canonical zone CLDR lists for a country.')
    ..writeln(
      'const Map<String, List<String>> kLumeCountryZones = '
      '<String, List<String>>{',
    );
  for (final MapEntry<String, List<String>> e in zones.entries) {
    out.writeln(
      "  '${e.key}': <String>[${e.value.map((String z) => "'$z'").join(', ')}],",
    );
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln(
      '/// The one civil time of a country that has exactly one — absent for',
    )
    ..writeln('/// a country with several (${several.join(', ')}).')
    ..writeln(
      'const Map<String, String> kLumeCountryCivilZone = <String, String>{',
    );
  for (final MapEntry<String, String> e in civil.entries) {
    out.writeln("  '${e.key}': '${e.value}',");
  }
  out.writeln('};');
  File(
    'lib/core/time/lume_country_zones.dart',
  ).writeAsStringSync(out.toString());
  stdout.writeln(
    'wrote ${zones.length} countries, ${civil.length} with one civil time: '
    'several in ${several.join(',')}',
  );
}
