// Generates lib/core/time/lume_zone_aliases.dart from the pinned `timezone`
// package: which identifiers in `latest_all` are IANA's canonical zones, and
// which are backward links, each with the canonical zone it names.
//
//   dart run scripts/generate_zone_aliases.dart
//
// Run only as part of a deliberate tzdb update (WORLD_CLOCK_TIMEZONE.md,
// "Updating the database"), and review the diff it produces.
//
// A link in the compiled database is a copy of its target's rules, so the
// identifiers that share one set of rules are one zone and its links. The
// canonical member of each set is the one the package lists among its
// canonical locations (generated from IANA's own zone list); the rest are
// aliases of it. A set with no listed member keeps every member as canonical
// — no alias is invented.

// The package's canonical list is not exported; this script, not the app,
// reads it.
// ignore: implementation_imports
import 'package:timezone/src/common_locations.dart' as tz_common;
import 'package:timezone/data/latest_all.dart' as tz_data;
import 'package:timezone/timezone.dart' as tz;
import 'dart:io';

String _signature(tz.Location l) => <String>[
  l.transitionAt.join(','),
  l.transitionZone.join(','),
  for (final tz.TimeZone z in l.zones)
    '${z.offset.inSeconds}/${z.isDst}/${z.abbreviation}',
].join('|');

void main() {
  tz_data.initializeTimeZones();
  final Map<String, tz.Location> all = tz.timeZoneDatabase.locations;
  final Set<String> listed = tz_common.commonLocations.toSet();

  final Map<String, List<String>> bySignature = <String, List<String>>{};
  for (final tz.Location l in all.values) {
    (bySignature[_signature(l)] ??= <String>[]).add(l.name);
  }

  final Map<String, String> aliases = <String, String>{};
  final Set<String> canonical = <String>{};
  for (final List<String> names in bySignature.values) {
    final List<String> heads = names.where(listed.contains).toList();
    if (heads.length != 1) {
      canonical.addAll(names);
      continue;
    }
    canonical.add(heads.single);
    for (final String n in names) {
      if (n != heads.single) aliases[n] = heads.single;
    }
  }

  final List<String> a = aliases.keys.toList()..sort();
  final List<String> c = canonical.toList()..sort();
  final StringBuffer out = StringBuffer()
    ..writeln(
      '// GENERATED by scripts/generate_zone_aliases.dart — do not edit.',
    )
    ..writeln(
      '// Timezone package 0.11.1, tzdb 2025c, data variant latest_all.',
    )
    ..writeln('// ${c.length} canonical identifiers, ${a.length} aliases.')
    ..writeln()
    ..writeln('/// The tzdb release these tables were generated from.')
    ..writeln("const String kLumeTzdbVersion = '2025c';")
    ..writeln()
    ..writeln('/// Backward links, each to the canonical zone it names.')
    ..writeln('const Map<String, String> kLumeZoneAliases = <String, String>{');
  for (final String k in a) {
    out.writeln("  '$k': '${aliases[k]}',");
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln('/// The canonical identifiers — what a new selection stores.')
    ..writeln('const Set<String> kLumeCanonicalZones = <String>{');
  for (final String k in c) {
    out.writeln("  '$k',");
  }
  out.writeln('};');
  File(
    'lib/core/time/lume_zone_aliases.dart',
  ).writeAsStringSync(out.toString());
  stdout.writeln(
    'wrote ${c.length} canonical, ${a.length} aliases, '
    '${all.length} identifiers in the database',
  );
}
